import { defineConfig, engines } from '@argo-video/cli';

export default defineConfig({
  baseURL: process.env.WTP_BASE_URL || 'http://localhost:5173',
  // jpeg-stitch writes the mp4 straight into .argo/; the default webm mode loses
  // the screencast when Playwright purges test artifacts on a passing test
  video: { width: 1280, height: 720, browser: 'chromium', captureMode: 'jpeg-stitch' },
  // clips are pre-generated by pregen-tts.mjs, so argo only sees cache hits
  tts: { engine: engines.kokoro({ dtype: 'q8', device: 'cpu' }) },
  export: { audio: { loudnorm: true } },
});
