#!/usr/bin/env python3
"""mir-pack <workDir> <artifactDir>      full pack
mir-pack <workDir> --theme-only         only tokens.css, theme.css and theme.js (mir-reflect calls this)

Turns <workDir>/tokens.json (W3C Design Tokens format) into:
  tokens.css   the values as plain CSS variables on :root
  theme.css    the same values as a Tailwind v4 @theme block
  theme.js     applyTheme(): sets the variables at runtime, so a page can swap looks
and, on a full pack, builds a shadcn registry (registry.zip) from <workDir>/registry/*.tsx,
zips everything (bundle.zip) and copies the files the platform collects into <artifactDir>.
Last line is MIR_OK or MIR_ERROR: <reason>.
"""
import json
import shutil
import sys
import zipfile
from pathlib import Path

# Token path prefix -> Tailwind v4 theme variable prefix. `--color-primary` gives `bg-primary`, and so on.
VARIABLE_PREFIX = {
    ("color",): "color",
    ("font", "family"): "font",
    ("font", "size"): "text",
    ("font", "weight"): "font-weight",
    ("radius",): "radius",
    ("spacing",): "spacing",
    ("shadow",): "shadow",
}
COLLECTED = ["original.png", "rebuild.png", "diff.png", "page.png"]
ITEM_SCHEMA = "https://ui.shadcn.com/schema/registry-item.json"

THEME_JS = """// Generated by Mirrored. Every design value in the component is a CSS variable,
// so swapping the look of a page is just setting those variables.
export const theme = %s

/** Applies a theme (this one by default) to an element and everything inside it. */
export function applyTheme(values = theme, root = document.documentElement) {
  for (const [name, value] of Object.entries(values)) root.style.setProperty(`--${name}`, value)
}

/** Undoes applyTheme. */
export function clearTheme(values = theme, root = document.documentElement) {
  for (const name of Object.keys(values)) root.style.removeProperty(`--${name}`)
}
"""


def fail(reason):
    print(f"MIR_ERROR: {reason}")
    sys.exit(1)


def css_value(value):
    if isinstance(value, dict) and "unit" in value:
        return f"{value['value']}{value['unit']}"
    if isinstance(value, dict):  # shadow
        return " ".join(css_value(value[k]) for k in ("offsetX", "offsetY", "blur", "spread", "color") if k in value)
    if isinstance(value, list):
        if value and isinstance(value[0], dict):
            return ", ".join(css_value(v) for v in value)
        return ", ".join(f'"{v}"' if " " in str(v) else str(v) for v in value)
    return str(value)


def flatten(node, path=()):
    """Yields (path, css value) for every token under node."""
    if "$value" in node:
        yield path, css_value(node["$value"])
        return
    for key, child in node.items():
        if not key.startswith("$") and isinstance(child, dict):
            yield from flatten(child, path + (key,))


def variable_name(path):
    for prefix, name in VARIABLE_PREFIX.items():
        if path[: len(prefix)] == prefix and len(path) > len(prefix):
            return "-".join((name,) + path[len(prefix) :])
    return None


def read_theme(work):
    tokens_path = work / "tokens.json"
    if not tokens_path.exists():
        fail(f"{tokens_path} does not exist")
    try:
        tokens = json.loads(tokens_path.read_text())
    except json.JSONDecodeError as error:
        fail(f"tokens.json is not valid JSON: {error}")
    theme, unknown = {}, []
    for path, value in flatten(tokens):
        name = variable_name(path)
        if name:
            theme[name] = value
        else:
            unknown.append(".".join(path))
    if unknown:
        fail(f"tokens outside the known groups (color, font.family, font.size, font.weight, radius, spacing, shadow): {', '.join(unknown[:5])}")
    if not any(name.startswith("color-") for name in theme):
        fail('tokens.json needs a top-level "color" group whose leaves have "$value"')
    return theme


def write_theme(work, theme):
    lines = "".join(f"  --{name}: {value};\n" for name, value in theme.items())
    (work / "tokens.css").write_text(f":root {{\n{lines}}}\n")
    (work / "theme.css").write_text(f"@theme {{\n{lines}}}\n")
    (work / "theme.js").write_text(THEME_JS % json.dumps(theme, indent=2))


def registry_items(work, theme):
    """One shadcn registry item per component file; each carries the theme, so one command is enough."""
    items = {}
    for file in sorted((work / "registry").glob("*.tsx")):
        if file.stem == "preview":
            continue
        items[file.stem] = {
            "$schema": ITEM_SCHEMA,
            "name": file.stem,
            "type": "registry:component",
            "title": file.stem.replace("-", " ").title(),
            "description": "Rebuilt from a live page by Mirrored.",
            "files": [{"path": f"registry/mirrored/{file.name}", "type": "registry:component", "content": file.read_text()}],
            "cssVars": {"theme": theme},
        }
    return items


def main(work_dir, target):
    work = Path(work_dir)
    theme = read_theme(work)
    write_theme(work, theme)
    if target == "--theme-only":
        print("MIR_OK")
        return

    out = Path(target)
    out.mkdir(parents=True, exist_ok=True)
    items = registry_items(work, theme)
    if items:
        with zipfile.ZipFile(out / "registry.zip", "w", zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("r/index.json", json.dumps({"items": [{"name": n, "type": i["type"]} for n, i in items.items()]}, indent=2))
            for name, item in items.items():
                archive.writestr(f"r/{name}.json", json.dumps(item, indent=2))

    with zipfile.ZipFile(out / "bundle.zip", "w", zipfile.ZIP_DEFLATED) as archive:
        for name in ("tokens.json", "tokens.css", "theme.css", "theme.js", "README.md"):
            if (work / name).exists():
                archive.write(work / name, name)
        for folder, prefix in (("registry", "components"), ("measure/assets", "assets")):
            for file in sorted((work / folder).glob("*")) if (work / folder).exists() else []:
                if file.is_file() and file.name != "tsconfig.json":
                    archive.write(file, f"{prefix}/{file.name}")
    shutil.copy(work / "tokens.json", out / "tokens.json")
    for name in COLLECTED:
        if (work / "measure" / name).exists():
            shutil.copy(work / "measure" / name, out / name)

    print(f"tokens: {len(theme)}  components: {len(items)}  bundle: {(out / 'bundle.zip').stat().st_size // 1024} KB")
    print("MIR_OK")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        fail("usage: mir-pack <workDir> <artifactDir> | mir-pack <workDir> --theme-only")
    main(*sys.argv[1:])
